from pydantic import BaseModel, Field, ValidationError, model_validator
from datetime import datetime
from enum import Enum


class ContactType(Enum):
    radio = "radio"
    visual = "visual"
    physical = "physical"
    telepathic = "telepathic"


class AlienContact(BaseModel):
    """
    Represents a recorded alien contact event and its verification status.

    This model includes contact identification, timing, location, signal
    characteristics, witness information, and message content. It is used for
    validating contact reports generated by monitoring systems
    or research logs.
    """

    contact_id: str = Field(..., min_length=5, max_length=15)
    timestamp: datetime
    location: str = Field(..., min_length=3, max_length=100)
    contact_type: ContactType
    signal_strength: float = Field(..., ge=0.0, le=10.0)
    duration_minutes: int = Field(..., ge=1, le=1440)
    witness_count: int = Field(..., ge=1, le=100)
    message_received: str | None = Field(None, max_length=500)
    is_verified: bool = False

    @model_validator(mode="after")
    def validate_contact(self) -> "AlienContact":
        # 1. The contact ID needs to start with 'AC'.
        if not self.contact_id.startswith("AC"):
            raise ValueError("contact_id must start with 'AC'")

        # 2. Physical contact must be verified.
        if self.contact_type == ContactType.physical and not self.is_verified:
            raise ValueError(
                "Physical contact reports must be verified"
            )

        # 3. Telepathy requires at least three witnesses
        if (
            self.contact_type == ContactType.telepathic
            and self.witness_count < 3
        ):
            raise ValueError(
                "Telepathic contact requires at least 3 witnesses"
            )

        # 4. A strong signal (> 7.0) requires message_received
        if self.signal_strength > 7.0 and not self.message_received:
            raise ValueError(
                "Strong signals (>7.0) "
                "must include a received message"
            )

        return self


def main() -> None:
    print("Alien Contact Log Validation")

    try:
        ac = AlienContact(
            contact_id="AC12345",
            timestamp=datetime.now(),
            location="Sector 7",
            contact_type=ContactType.radio,
            signal_strength=5.5,
            duration_minutes=30,
            witness_count=4,
            message_received="Hello from beyond.",
            is_verified=True
        )

        print("Valid contact report:")
        print(f"ID: {ac.contact_id}")
        print(f"Type: {ac.contact_type.value}")
        print(f"Location: {ac.location}")
        print(f"Signal: {ac.signal_strength}")
        print(f"Duration: {ac.duration_minutes} minutes")
        print(f"Witnesses: {ac.witness_count}")
        print(f"Message: '{ac.message_received}'")

    except ValidationError as e:
        print("Unexpected validation error:", e)

    print("\nExpected validation error:")
    try:
        AlienContact(
            contact_id="AC99999",
            timestamp=datetime.now(),
            location="Sector X",
            contact_type=ContactType.telepathic,
            signal_strength=8.0,
            duration_minutes=10,
            witness_count=1,  # invalid
            message_received="Mind link established.",
            is_verified=True
        )
    except ValidationError as e:
        for err in e.errors():
            print(err["msg"])


if __name__ == "__main__":
    main()
